version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/bounsweAss7API
hooks:
  AfterInstall:
    - location: scripts/fix_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_application.sh
      timeout: 300
      runas: ec2-user
