dist: xenial

language: python

python:
  - "3.7"

env:
  -DJANGO=2.2.1

install:
  - cd practice-app
  - pip install -r requirements.txt

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      repo: bounswe/bounswe2019group9
      branch: travis-deploy-fix

script:
  - python manage.py test

branches:
  only:
    - travis-deploy-fix