matrix:
  include:
    - language: python
      dist: xenial
      python:
        - "3.7"
      env:
        -DJANGO=2.2.1
      install:
        - cd practice-app
        - pip install -r requirements.txt
      deploy:
        - provider: s3
          access_key_id: $PRACTICE_APP_AWS_ACCESS_KEY
          secret_access_key: $PRACTICE_APP_AWS_SECRET_KEY
          local_dir: dpl_cd_upload
          skip_cleanup: true
          on: &2
            repo: bounswe/bounswe2019group9
            branch: master
          bucket: bounswe-ass7-bucket
          region: eu-central-1
        - provider: codedeploy
          access_key_id: $PRACTICE_APP_AWS_ACCESS_KEY
          secret_access_key: $PRACTICE_APP_AWS_SECRET_KEY
          bucket: bounswe-ass7-bucket
          key: latest.zip
          bundle_type: zip
          application: bounsweAss7API
          deployment_group: bounsweAss7APIDeploymentGroup
          region: eu-central-1
          on: *2
      script:
        - zip -r latest *
        - mkdir -p dpl_cd_upload
        - mv latest.zip dpl_cd_upload/latest.zip
        - python manage.py test
      branches:
        only:
          - master
    - language: java
      dist: xenial
      jdk: oraclejdk8
      install:
        - cd backend
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      script:
        - ./mvnw clean install -B
        - mv target/language-learning-platform-*.jar language-learning-platform.jar
        - mv server-conf/appspec.yml appspec.yml
        - zip -r latest appspec.yml language-learning-platform.jar
        - mkdir -p dpl_cl_upload
        - mv latest.zip dpl_cd_upload/latest.zip
      deploy:
        - provider: s3
          access_key_id: $BACKEND_AWS_ACCESS_KEY
          secret_access_key: $BACKEND_AWS_SECRET_KEY
          local_dir: dpl_cd_upload
          skip_cleanup: true
          on: &2
            repo: bounswe/bounswe2019group9
            branch: master
          bucket: bounswe-backend-bucket
          region: eu-central-1
        - provider: codedeploy
          access_key_id: $BACKEND_AWS_ACCESS_KEY
          secret_access_key: $BACKEND_AWS_SECRET_KEY
          bucket: bounswe-backend-bucket
          key: latest.zip
          bundle_type: zip
          application: bounsweBackend
          deployment_group: bounsweBackendDeploymentGroup
          region: eu-central-1
          on: *2

