dist: xenial

language: python

python:
  - "3.7"

env:
  -DJANGO=2.2.1

install:
  - cd practice-app
  - pip install -r requirements.txt

virtualenv:
  system_site_packages: true

deploy:
  - provider: script
    script: "curl -H 'commit: $TRAVIS_COMMIT' -H 'description: $TRAVIS_COMMIT_MESSAGE' bounswe.tanzen.ml/ass7"
    on:
      repo: bounswe/bounswe2019group9
      branch: practice-app-skeleton

script:
  - cd practice-app
  - python manage.py test
