version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: server-conf/fix_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server-conf/restart_application.sh
      timeout: 300
      runas: root
